const fs = require('fs');
const path = require('path');
const { jsPDF } = require('jspdf');

const generateAstrologerPDF = async (matchId, profileA, profileB, matchResult) => {
  // Mock PDF generation for MVP
  // In reality this would use html2canvas + jsPDF to render charts and layout.
  return new Promise((resolve, reject) => {
    try {
      const doc = new jsPDF();
      doc.setFontSize(20);
      doc.text("Jatham Match Report", 20, 20);
      
      doc.setFontSize(12);
      doc.text(`Match ID: ${matchId}`, 20, 30);
      doc.text(`Groom: ${profileA.candidateName} (${profileA.astroData.nakshatraName})`, 20, 40);
      doc.text(`Bride: ${profileB.candidateName} (${profileB.astroData.nakshatraName})`, 20, 50);
      
      doc.text(`Overall Score: ${matchResult.overallScore}/100`, 20, 60);
      doc.text(`Status: ${matchResult.hasHardReject ? 'HARD REJECT DETECTED' : 'APPROVED FOR REVIEW'}`, 20, 70);

      // Disclaimer
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text("This compatibility analysis is generated by a rule-based system and is intended as a decision", 20, 90);
      doc.text("support tool only. It does not constitute astrological advice or a guarantee of marital compatibility.", 20, 95);

      const pdfDir = path.join(__dirname, '../../data/pdfs');
      if (!fs.existsSync(pdfDir)) {
        fs.mkdirSync(pdfDir, { recursive: true });
      }

      const filePath = path.join(pdfDir, `${matchId}.pdf`);
      doc.save(filePath);
      
      resolve(filePath);
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = {
  generateAstrologerPDF
};
